language: node_js
node_js:
- lts/*
install: |-
  npm ci
  npm install -g codecov
script: |-
  npm run build
  ./node_modules/.bin/nyc report --reporter lcovonly -- -R spec
  codecov
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  echo $'Commit message: '$TRAVIS_COMMIT_MESSAGE
  echo $'**Change log:**<br/>'${log//$'\n'/<br/>}
branches:
  only:
    - master
before_deploy: |-
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  export BODY=$'**Change log:**<br/>'${log//$'\n'/<br/>}
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: hYm3aKpIA4vxI+kQMK6WTGSglefIxyffjBU6xeWa7tBiVJb4YrJHOiFMvI43zW3ypP/FeW16iWP57FADfxYxI3yyY8d19qY+HzBClFY6TWScz0nK6eX0mlbWkz9KxxtjVEar461k4lxYQA8L5lqnaH/AiG0vlZqycnWIV0sB+zQF1KINoSf7ZnSHpzkto36sQYEcamSlNp7aZ5fnHpyt70/ZLqwzf6qP+b6miIc91Cwcu1ahHPo1Tv0K8yznxDAKbmVEa4pxo/y3LT1IMsHDWtSbo6BVJQDbvp5pCGmL8nqlLwQsMMRjvhk5qcq0Yf/YK0MqJ9QIYGAn48tjl+RqeHanXd4NTqGGGRHOtS/1kBJuUfZz6qIvZwe6v3XwoYh32KAaiN/dc7PWMvZ6Sm44BqZaIxxfGvPDSvuEMy1nIBONk9OjS4uwoQg//tAzPZyB3TkQ67zscH1TKIiwk7A6lDTzwS/b2Un5jOlzkWY0WvGbw9KHlfx2tdZGYauHLurDs19/IU149H3H+srqhymB1JwrPkCMP2VVwyYqygi15vQ6zexiN7nja+5J816hmJgzCiEfdmxfAdFe9qatyrrGmqS3jL9gHzwxCxngSMF91VfMG9DZ4kPvvlf+DDLn7HyAEigxUopiZoHv7mcejEzbP57wIArtqA+shXh0eSyc+6U=
    file: README.md
    name: Release $TRAVIS_COMMIT_MESSAGE
    tag_name: $TRAVIS_COMMIT_MESSAGE
    body: $BODY
    on:
      repo: Guseyn/wall
      branch:
        - master
      condition: $TRAVIS_COMMIT_MESSAGE =~ ^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$
  - provider: npm
    email: guseynism@gmail.com
    api_key:
      secure: j6dJjSiJm5gYqm6k08ZWGjKwq2OFZTxTYnaSnQhqRK/aevL2xtV9hH66GBSWP2+8xJnYNvzXGm8r9yabeL/pgl2qWDi09amW254waXpmy7T7fYLv+HhLb4RzaDZik18OG5VHGfXJjtKkr+cYbA2mHi04e2lbGFy78rLwugDkombSvXTyDwocuy3nIeuV1lHK8ssKfbyu1cP9/hfY/cJbprrKopCzFmmNrLYtfsVbHQ9EzARSNAI7AN0zfN1cDSN77/B5xfhCfrIJBKTkK1thSbHBcw0YxaFSEZRBiBB0Mxjye4OUIa1AaReLRYn35FalDPevGjIxo3bhjLnfVjLwAXunNiTnZF2YfZkPf/8EBCH8oDNnmXQLigDTC2Do3E+yALYEBoS9ShyZai46SzZkUwN8S4iRK/64bMfOq8D2lIWZxUO/W1IPK8M1aofu6l1apbqFlgghIOwGf4SJzpbK4P4SYCBaLdrml6GQMrmlsUoSLCrhIqP7MNNDIeiXncflB7cDUVLE1yBvyroBB7HY6uoXYUr3TAjgTioZ7TiXJfeURPyxps72gCv2vatx/YcILb/XwSCAraRtIpYzd9qcB/A7+vJsebxnojj66RqP8issFSpDKqflO8rypExHKdpiommn8d1zgCyVjZW5RjmcM7pxOfII/TdnKoXrL34qOKM=
    on:
      repo: Guseyn/wall
      branch:
        - master
      condition: $TRAVIS_COMMIT_MESSAGE =~ ^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$
